HillwoodEmpire2022/E-commerce-frontend

- src/components/home/Header/Header.js
- src/components/home/NewArrivals/NewArrivals.js
- src/components/home/NewArrivals/NewArrivals1.js
- src/components/home/Products/Badge.js
- src/components/home/Products/Product.js
- src/components/home/Products/ProductsGridContainer.js
- src/components/home/Products/ProductsSection.js
- src/components/home/Products/ProductsSliderContainer.js
- src/components/pageProps/productDetails/ProductImages.js
- src/components/pageProps/productDetails/ProductMainInfo.js
- src/components/pageProps/productDetails/ProductSecondaryInfo.js
- src/components/pageProps/productDetails/SmallImagesContainer.js
- src/pages/ProductDetails/ProductDetails.js
> Product details page

- src/redux/productsSlice.js
- src/redux/store.js
- src/redux/userSlice.js
> add user reducer to redux

- src/Layouts/IndexLayout.js
- src/pages/Authentication/SignIn.js
> fix CORS headers on google signin success

- src/Layouts/IndexLayout.js
> fix allowing credential triggering CORS preflight

- src/pages/Authentication/SignIn.js
> handle sign in errors

- src/Layouts/IndexLayout.js
- src/pages/Authentication/SignIn.js
- src/pages/Authentication/SignUp.js
> implement navigating to home page on successful auth by google

- src/Layouts/IndexLayout.js
> fix userInfo not defined

- src/components/home/Header/UserAvatarDropdown.js
> implement logout for passport google auth

- .env.example
- src/Layouts/IndexLayout.js
- src/components/home/Header/Header.js
- src/components/home/Header/UserAvatarDropdown.js
- src/pages/Authentication/SignIn.js
- src/redux/userSlice.js
> fix logging out google account not navigating to index

- src/Layouts/IndexLayout.js
- src/components/home/Header/Header.js
- src/components/home/Header/HeaderBottom.js
- src/components/home/Header/UserAvatarDropdown.js
- src/pages/Authentication/SignIn.js
> fix signout not working and reduce props drilling for avatarDropDown

- package-lock.json
- package.json
- src/components/designLayouts/AlertComponent.js
- src/components/home/Header/HeaderBottom.js
- src/pages/Authentication/SignIn.js
- src/pages/Authentication/SignUp.js
- tailwind.config.js
> implement displaying error messages on sign up and sing in

- src/Layouts/IndexLayout.js
> fix google oauth logout integration

- package-lock.json
- package.json
- src/App.js
- src/Layouts/IndexLayout.js
- src/components/home/Header/Header.js
- src/components/loader/Loader.css
- src/components/loader/Loader.js
> Create loader for the e-commerce website which will exists only once you load page
> Ft loader UI

- src/Layouts/IndexLayout.js
> Remove error which well on loader
> Remove errors

- package.json
> fix CORS issue for backend accessing fronted

- package-lock.json
- package.json
- public/index.html
- src/components/Banner/Banner.js
- src/components/home/Header/HeaderBottom.js
- src/components/imageslider/ImageSlider.css
- src/components/imageslider/ImageSlider.js
- src/components/nestedList/NestedList.js
> Ft category

- src/components/Banner/Banner.js
- src/components/home/Header/HeaderBottom.js
- src/components/imageslider/ImageSlider.js
- src/components/nestedList/NestedList.js
> Make responsive for banner, style category and add category above banner
> Ft solve banner

- src/components/home/Products/Badge.js
- src/components/home/Products/Product.js
- src/components/home/ProductsSections/SampleNextArrow.js
- src/components/home/ProductsSections/SamplePrevArrow.js
> Merge with main branch to resolve conflict and get content from other branches
> Merge with main

- src/components/Currency/CurrencyProvider/CurrencyProvider.js
- src/components/Currency/DisplayCurrency/DisplayCurrency.js
- src/components/home/Header/Header.js
- src/components/home/Products/Product.js
- src/index.js
> Create currency converter for product amount and currency
> Ft currency converter

- src/components/Banner/Banner.js
- src/components/home/Products/Badge.js
- src/components/home/ProductsSections/NewArrivals.js
- src/pages/Default/Cart/ItemCard.js
- src/redux/productsSlice.js
- src/redux/userSlice.js
> implement increasing and decreasing cart item quantity

- package-lock.json
- package.json
- src/App.js
- src/components/home/Header/HeaderBottom.js
- src/components/home/Products/Product.js
- src/components/home/ProductsSections/Recommendations.js
- src/components/pageProps/productDetails/CheckoutDetails.js
- src/components/pageProps/productDetails/ProductImages.js
- src/components/pageProps/productDetails/ProductMainInfo.js
> fix product details page rendering

- src/App.js
- src/components/home/ProductsSections/Recommendations.js
- src/components/pageProps/Authentication/SignInForm.js
- src/components/pageProps/Authentication/SignUpForm.js
> fix recommendations component not rendering product cards

- src/App.js
> Products cart

- src/App.js
- src/components/home/Header/Header.js
- src/components/pageProps/Authentication/SignInForm.js
> retrieve user information on successful google authentication

- src/App.js
> fix retrieving user info on successful google auth

- src/App.js
- src/pages/Default/ProductDetails/ProductDetails.js
> fix constant fetching of related products on details page

- src/App.js
> fix retrieving user information on successful google auth

- package-lock.json
- package.json
> upgrade axios to latest

- package-lock.json
- package.json
- src/App.js
> add axios interceptors

- package-lock.json
- package.json
- src/components/Banner/Banner.js
- src/components/nestedList/NestedList.js
> integrate database categories

- src/components/Banner/Banner.js
- src/components/home/AllProducts/CategoryFilteredProducts.js
- src/components/home/Header/Header.js
- src/components/nestedList/NestedList.js
- src/components/pageProps/productDetails/ProductSecondaryInfo.js
- src/pages/Account/Home/UserHome.js
- src/pages/Default/Home/Home.js
> implement categories and subcategories filtering

- src/APIs/UserAPIs.js
- src/components/Banner/Banner.js
- src/components/home/AllProducts/AllProducts.js
- src/components/home/AllProducts/CategoryFilteredProducts.js
- src/components/home/Header/UserAvatarDropdown.js
- src/components/home/ProductsSections/Recommendations.js
- src/components/nestedList/NestedList.js
- src/components/profile/photoupdate/Updateimage.js
- src/pages/Account/Home/UserHome.js
- src/pages/Account/Profile/CompanyModel/CompanyModel.js
- src/pages/Account/Profile/SellerProfile.js
- src/redux/Reducers/userReducers.js
> Ft update profile photo

- src/APIs/Oreders.js
- src/App.js
- src/components/home/Header/UserAvatarDropdown.js
- src/pages/Default/Cart/Cart.js
- src/pages/orders/orderTable.js
- src/pages/orders/orders.js
- src/redux/Reducers/OrderReducer.js
- src/redux/store.js
- tailwind.config.js
> Ft create orders

- src/APIs/UserAPIs.js
- src/pages/Account/Profile/CompanyModel/CompanyModel.js
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Account/Profile/userinfo.js
- src/pages/Default/Cart/Cart.js
- src/redux/Reducers/userReducers.js
- src/redux/store.js
-implement redux toolkit
-update profile userinfo integration
> create update user info model

- src/APIs/Oreders.js
- src/App.js
- src/components/Header/UserAvatarDropdown.js
- src/context/UserContex.js
- src/dashboard/Components/Orders/Order.js/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Orders/styles.css
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Account/Profile/SellerProfile.js
- src/redux/Reducers/OrderReducer.js
- src/redux/store.js
-fix active route on dashboard
> implementation of orders on dashboard

- src/components/ProductsCategories.js
- src/dashboard/Common/handleOrderTotal.js
- src/dashboard/Components/Contract/Contract.js
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Layouts/LayoutDesign.js
- src/index.css
- src/pages/Account/Profile/CompanyModel/CompanyModel.js
- src/pages/Account/Profile/SellerProfile.js
> Ft dashboard responsiveness

- public/index.html
- src/Apis/Company.jsx
- src/components/CLOUDIMAGES/App.css
- src/components/CLOUDIMAGES/Button.js
- src/components/CLOUDIMAGES/UploadWidget.js
- src/components/Header/UserAvatarDropdown.js
- src/components/ProductsCategories.js
- src/dashboard/Apis/Company.jsx
- src/dashboard/Apis/Product.jsx
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/pages/ProductDetails/ProductMainInfo.js
- src/pages/ProductDetails/ProductSecondaryInfo.js
> implelemnt image upload using clodinary Upload widget

- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
> get orders item to all

- .env.example
- src/APIs/Oreders.js
- src/common/productspossibleSizes.js
- src/components/CLOUDIMAGES/UploadWidget.js
- src/dashboard/Components/Category/ActionButton/ActionButton.js
- src/dashboard/Components/Category/Category.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Layouts/LayoutDesign.js
- src/redux/Reducers/OrderReducer.js
-implement orderby updated at on product
-cestomize color on upload images widget
> implement orders load fix

- src/App.js
- src/dashboard/Components/Product/Product.js
- src/pages/PageNotFound.js
> implement page not found page

- src/dashboard/Components/Loader/LoadingSpin.jsx
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/users/UsersTable.js
- src/dashboard/Components/users/style.css
- src/dashboard/Components/users/userActions/updatemodel.js
- src/index.css
- src/pages/Users.js
- src/redux/Reducers/usersSlice.js
-handle update user role on dahsboard
> -create userupdate model

- src/components/Header/SearchBar.js
- src/pages/ProductDetails/ProductMainInfo.js
- src/pages/ProductDetails/SmallImagesContainer.js
> -fix colorname error

- src/dashboard/Components/Product/ProductModel/ProductModel.js
> -fix alert check variation for product create

- src/APIs/Product.js
- src/APIs/UserAPIs.js
- src/common/productspossibleSizes.js
- src/components/CLOUDIMAGES/UploadWidget.js
- src/dashboard/Apis/Product.jsx
- src/dashboard/Components/Button/Modelfooter.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Redux/ReduxSlice/Slice.js
- src/pages/Account/Profile/CompanyModel/CompanyModel.js
- src/redux/Reducers/OrderReducer.js
> Ft admin dash update product

- src/App.js
- src/components/Footer/FooterBottom.js
- src/pages/Default/About/About.js
> fix redirect product

- src/App.js
- src/components/Authentication/SignInForm.js
- src/components/profile/photoupdate/Updateimage.js
- src/dashboard/Apis/Product.jsx
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Redux/ReduxSlice/Slice.js
- src/dashboard/Redux/ReduxSlice/createProduct.js
- src/pages/Account/Profile/SellerProfile.js
> handle update product state

- src/components/profile/photoupdate/Updateimage.js
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Layouts/LayoutDesign.js
- src/index.css
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Cart.js
- src/pages/ProductDetails/ProductSecondaryInfo.js
> Fix daboard responsiveness

- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
-manage subcategory to depend on category while updating
> handle update product category

- src/App.js
- src/dashboard/Components/Button/AvtionButton.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Components/users/UsersTable.js
> Fix product update

- src/components/Authentication/ResetPasswordForm.js
- src/components/Authentication/SignInForm.js
- src/components/Authentication/SignUpForm.js
- src/dashboard/Common/index.js
- src/dashboard/Components/Chart/DashboardTopCard.js
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Cart.js
> Fix product card action

- src/dashboard/Common/index.js
- src/dashboard/Components/Chart/DashboardTopCard.js
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ActionButton copy/ActionButton.js
- src/dashboard/Components/Product/Product.js
> implement seller view dashboard

- src/dashboard/Components/Chart/DashboardTopCard.js
- src/dashboard/Components/Dashboard/Dashboard.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Layouts/LayoutDesign.js
> Fix dahdoard titles

- src/dashboard/Components/Chart/DashboardTopCard.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/index.css
> fix closemodel

- package-lock.json
- package.json
- src/App.js
- src/common/index.js
- src/components/Banner/Banner.js
- src/components/Header/Header.js
- src/components/Header/SearchBar.js
- src/components/homePageCategories/HomePageCategories.js
- src/dashboard/Common/index.js
- src/dashboard/Components/Chart/DashboardTopCard.js
- src/dashboard/Layouts/LayoutDesign.js
- src/index.css
- src/pages/Account/Profile/Googlemap/getLocation.js
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Cart.js
> Ft google map

- src/components/Footer/Footer.js
- src/components/home/Footer/Footer.js
- src/components/pageProps/shopPage/ProductBanner.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/components/pageProps/shopPage/shopBy/Brand.js
- src/components/pageProps/shopPage/shopBy/Price.js
- src/pages/Default/Shop/Shop.js
> Fix shop responsiveness

- src/pages/Cart.js
> Fix payment integration

- src/pages/Account/Profile/Googlemap/getLocation.js
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Cart.js
> -add space between fields

- src/dashboard/Components/Product/Product.js
> fit:product action's column yo be in the middle

- src/components/Header/Header.js
- src/pages/Cart.js
-make display column on cart
move proceed checkout button
> fix:cart-responsiveness

- public/index.html
- src/components/loader/Loader.js
- src/dashboard/Layouts/LayoutDesign.js
> change logos

- src/components/Banner/Banner.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Default/Shop/Shop.js
> handle display adds on small screen

- src/APIs/UserAPIs.js
- src/components/homePageCategories/HomePageCategories.js
- src/pages/Account/Profile/Actions/deleteAccount.jsx
- src/pages/Account/Profile/SellerProfile.js
handle implement delete acount
> create deelte acount model

- src/APIs/UserAPIs.js
- src/dashboard/Components/users/UsersTable.js
- src/dashboard/Components/users/userActions/deleteUserAccount.jsx
> implement admin delete user account

- src/components/Authentication/SignInForm.js
- src/components/Authentication/requestActivationEmail.js
- src/dashboard/Components/users/UsersTable.js
validate form input
add required buttton to get email
inform user about errors and successful activation email sent to them
> creact activate reqest by email 

- public/index.html
- src/dashboard/Components/Orders/orders.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Layouts/LayoutDesign.js
- src/index.css
- src/pages/Account/Profile/Googlemap/GoogleMap.js
- src/pages/Account/Profile/SellerProfile.js
> Hot fix profile

- src/components/homePageCategories/HomePageCategories.js
> change subcategory to have grid display

- src/App.js
- src/dashboard/Common/index.js
- src/dashboard/Components/ProductClass/ActionButton/ActionButton.js
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Components/ProductClass/AddCategory/SubCategory.js
- src/dashboard/Components/ProductClass/CategoryModel/CategoryModel.js
- src/dashboard/Components/ProductClass/ProductClass.jsx
- src/dashboard/Components/ProductClass/UpdateModel/UpdateModel.js
- src/dashboard/Components/ProductClass/style.css
- src/dashboard/Components/index.js
- src/dashboard/Layouts/LayoutDesign.js
- src/dashboard/Redux/ReduxSlice/ProductClass.js
- src/redux/store.js
create product class store
hand le product class state after create
> create product class model

- src/App.js
- src/dashboard/Components/ProductBrand/ActionButton/ActionButton.js
- src/dashboard/Components/ProductBrand/AddCategory/Category.js
- src/dashboard/Components/ProductBrand/AddCategory/SubCategory.js
- src/dashboard/Components/ProductBrand/CategoryModel/CategoryModel.js
- src/dashboard/Components/ProductBrand/ProductBrand.jsx
- src/dashboard/Components/ProductBrand/UpdateModel/UpdateModel.js
- src/dashboard/Redux/ReduxSlice/ProductBrand.slice.js
- src/dashboard/Redux/ReduxSlice/ProductClass.js
- src/redux/store.js
fetch all brands
create brand model and update brand state after create
> feature product brand

- src/dashboard/Apis/Categories.js
- src/dashboard/Components/Category/AddCategory/Category.js
- src/dashboard/Redux/ReduxSlice/ProductBrand.slice.js
handle get product class before create category
> feature change category

- src/dashboard/Components/Category/Category.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/ProductClass/ProductClass.jsx
> Fix product create model

- src/components/homePageCategories/HomePageCategories.js
- src/pages/Default/Home/Home.js
- src/pages/Default/Shop/Shop.js
- src/pages/ProductDetails/ProductDetails.js
> handle get product class on home page

- src/components/homePageCategories/HomePageCategories.js
>  change ?productClass on shop

- src/components/homePageCategories/HomePageCategories.js
- src/pages/Default/Shop/Shop.js
> change get products by queryparams

- src/dashboard/Components/Product/Product.js
- src/pages/Default/Shop/Shop.js
- src/pages/Default/Shop/ShopProducts.js
> handle change onloader

- src/App.js
- src/components/home/AllProducts/AllProducts.js
- src/components/pageProps/shopPage/ProductBanner.js
- src/components/pageProps/shopPage/shopBy/Brand.js
implement get product by brand name
hide shop top header
> change home page loader

- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/components/pageProps/shopPage/ProductBanner.js
- src/components/pageProps/shopPage/shopBy/NavTitle.js
- src/pages/Default/Shop/Shop.js
handle remove other searchparams query
> fix product filter by product class, category on top of shoppage

- src/dashboard/Components/ProductClass/ActionButton/ActionButton.js
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Components/ProductClass/ProductClass.jsx
- src/dashboard/Redux/ReduxSlice/ProductClass.js
implement delete product class
> implement update product class action

- src/components/MobileCategoryNav.js
- src/components/ProductsCategories.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/ProductSubCategory.js
- src/components/pageProps/shopPage/ProductBanner.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/pages/Home.js
> Fix fetch seller  and filter products

- src/components/homePageCategories/HomePageCategories.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/ProductSubCategory.js
- src/components/pageProps/shopPage/Accordions/productBrand.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/dashboard/Components/Dashboard/OrdersTable.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/pages/Cart.js
> Fix dashboard orders

- src/components/ProductsCategories.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/Default/Shop/Shop.js
- src/pages/Payment/cardpayment/card.js
- src/pages/Payment/cardpayment/validation.js
- src/pages/ProductDetails/CheckoutDetails.js
> Ft checkout card

- src/App.js
- src/components/Header/Header.js
- src/components/home/AllProducts/WishlistAllProducts.js
- src/components/home/Products/Badge.js
- src/components/home/Products/Product.js
- src/components/home/Products/wishlistProduct.js
- src/constants/index.js
- src/pages/Default/About/About.js
- src/pages/ProductDetails/ProductDetails.js
- src/pages/ProductDetails/ProductImages.js
- src/pages/Wishlist.js
- src/redux/Reducers/wishlist.js
- src/redux/store.js
> Ft wishlist

- src/components/home/Products/Product.js
- src/pages/Account/Profile/Actions/deleteAccount.jsx
- src/pages/Payment/cardpayment/card.js
- src/pages/Payment/cardpayment/validation.js
> Fix card address

- src/components/Currency/DisplayCurrency/DisplayCurrency.js
- src/components/home/Products/Badge.js
- src/components/home/Products/Product.js
- src/components/home/Products/wishlistProduct.js
- src/pages/ProductDetails/CheckoutDetails.js
- src/pages/ProductDetails/ProductMainInfo.js
- src/util/discountedFinalPrice.js
implement add discount percentage to cart and wishlist storage
> handle calculate discount and display discount on products card

- src/components/home/Products/Product.js
- src/components/home/Products/wishlistProduct.js
- src/components/homePageCategories/HomePageCategories.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/OrdersTable.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/ProductDetails/ProductDetails.js
- src/pages/ProductDetails/ProductImages.js
- src/redux/Reducers/wishlist.js
> Fix delivery

- src/pages/Checkout.js
> handle show delivery message outside kigali

- src/components/Header/Header.js
- src/components/ProductsCategories.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/ProductSubCategory.js
- src/components/pageProps/shopPage/Accordions/productBrand.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/components/pageProps/shopPage/shopBy/NavTitle.js
- src/pages/Default/Shop/Shop.js
> hide shop by category on mobile home screen

- src/pages/Payment/cardpayment/card.js
> implement redirect on  3D card

- package-lock.json
- package.json
- src/App.js
- src/components/Header/Header.js
- src/components/pageProps/shopPage/ProductBanner.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/components/pageProps/shopPage/shopBy/Brand.js
- src/dashboard/Components/Orders/Order/singleOrder.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
- src/dashboard/Components/Orders/Ordersv2/orders.js
- src/dashboard/Components/Orders/Ordersv2/single-order/order.js
- src/dashboard/Components/index.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Checkout.js
- src/pages/Default/Shop/Shop.js
> Fix order design

- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Checkout.js
> add product class and brand on update product

- src/components/Header/Header.js
- src/components/Header/SearchBar.js
- src/components/Header/UserAvatarDropdown.js
- src/pages/Wishlist.js
change search component to show on mobile  header or on medium screen position logo on mobile viewport to the top
> hide sidebar search on mobile

- src/dashboard/Components/ProductClass/ActionButton/ActionButton.js
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Components/ProductClass/ProductClass.jsx
> handle get defaulvalues when user click on update product class action

- src/dashboard/Components/ProductBrand/ActionButton/ActionButton.js
- src/dashboard/Components/ProductBrand/AddCategory/Category.js
- src/dashboard/Components/ProductBrand/ProductBrand.jsx
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Redux/ReduxSlice/ProductBrand.slice.js
- src/dashboard/Redux/ReduxSlice/ProductClass.js
> create product update and delete redux slices

- src/components/Header/Header.js
- src/components/Header/SearchBar.js
- src/dashboard/Components/Product/Product.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Redux/ReduxSlice/ProductBrand.slice.js
> Fix product commission

- src/dashboard/Components/users/UsersTable.js
> implement search users

- src/APIs/Product.js
- src/Apis/Product.jsx
- src/dashboard/Apis/Product.jsx
- src/dashboard/Components/Button/AvtionButton.js
- src/dashboard/Components/Orders/Order/updateorderstatus.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
implement stop propagation on click
chnage order status
> import update model and create other functions on orders card

- package-lock.json
- package.json
- src/components/CLOUDIMAGES/Button.js
- src/components/CLOUDIMAGES/UploadWidget.js
- src/components/home/Products/Product.js
- src/components/home/Products/ProductsGridContainer.js
- src/components/home/Products/wishlistProduct.js
- src/index.css
> Ft product card layout

- src/components/CLOUDIMAGES/UploadWidget.js
- src/components/Footer/FooterBottom.js
- src/components/pageProps/Breadcrumbs.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/productBrand.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/pages/Default/About/About.js
- src/pages/ProductDetails/ProductImages.js
- src/pages/ProductDetails/ProductSecondaryInfo.js
handle get cloudinary best quality image on product info url
> handle change on product details image

- src/dashboard/Components/Product/ProductModel/ProductModel.js
> add seller commission to the create product model

- src/components/Header/SearchBar.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
> Fix update product

- src/components/CLOUDIMAGES/UploadWidget.js
- src/dashboard/Components/Orders/Order/repay-order.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
- src/pages/Checkout.js
- src/pages/Payment/cardpayment/card.js
- src/pages/Wishlist.js
> implement order repay with card

- src/dashboard/Components/Orders/Order/repay-order.js
- src/pages/Payment/cardpayment/card.js
> fix order id on props

- package-lock.json
- package.json
- src/components/Header/SearchBar.js
- src/dashboard/Components/Orders/Order/download-receipt.js
- src/dashboard/Components/Orders/Order/repay-order.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
> Ft delivery note

- src/components/ProductsCategories.js
- src/dashboard/Components/Orders/Order/download-receipt.js
- src/pages/ProductDetails/ProductSecondaryInfo.js
> fix  cloudinary image

- src/APIs/react-query/featured-product.js
- src/components/Banner/Banner.js
- src/components/Header/Header.js
- src/components/Header/SearchBar.js
- src/components/ProductsCategories.js
- src/components/imageslider/ImageSlider.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/pages/Default/Home/Home.js
> fix search & featured product

- src/components/Banner/Banner.js
- src/components/imageslider/ImageSlider.js
- src/dashboard/Components/Orders/Ordersv2/single-order/order.js
- src/pages/Checkout.js
- src/pages/ProductDetails/ProductImages.js
- src/pages/ProductDetails/SmallImagesContainer.js
> Fix images

- src/APIs/UserAPIs.js
- src/APIs/react-query/featured-product.js
- src/components/Footer/FooterBottom.js
- src/components/ProductsCategories.js
- src/components/category-images-cards/category.js
- src/dashboard/Components/Orders/Order/download-receipt.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Account/Profile/Actions/deleteAccount.jsx
- src/pages/Account/Profile/SellerProfile.js
- src/pages/Account/Profile/my-address-modal.js
- src/pages/ProductDetails/ProductImages.js
- src/redux/Reducers/user-address.js
- src/redux/store.js
> fix profile

- src/components/category-images-cards/category.js
- src/components/homePageCategories/HomePageCategories.js
- src/dashboard/Components/ProductClass/ActionButton/ActionButton.js
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Components/ProductClass/ProductClass.jsx
- src/dashboard/Redux/ReduxSlice/ProductClass.js
> feature categories icons

- package-lock.json
- package.json
- src/components/Banner/Banner.js
- src/components/Header/Header.js
- src/components/ProductsCategories.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/image-resizer.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/index.css
- src/pages/Default/Shop/Shop.js
> Image resizer

- src/components/Footer/FooterBottom.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/updateproductModel.js
- src/pages/ProductDetails/ProductSecondaryInfo.js
> add attributes field to the create product form

- src/dashboard/Components/Orders/Order/repay-order.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
> change order repay api

- src/App.js
- src/context/UserContex.js
- src/pages/ProductDetails/ProductDetails.js
> implement get related product on single product page

- src/components/ProductsCategories.js
- src/components/home/Products/ProductsGridContainer.js
- src/dashboard/Components/users/UsersTable.js
- src/pages/Users.js
- src/redux/Reducers/usersSlice.js
> fix hide grid product container

- src/APIs/Oreders.js
- src/dashboard/Components/Orders/Ordersv2/orders.js
- src/dashboard/Components/pagination/pagination.js
- src/dashboard/Components/users/UsersTable.js
- src/pages/Users.js
- src/redux/Reducers/OrderReducer.js
- src/redux/Reducers/usersSlice.js
change users initialstate to have elemnt
paginate users table
> feature:  pagination reusable component

- src/APIs/Oreders.js
- src/dashboard/Components/Orders/Ordersv2/orders.js
- src/dashboard/Components/users/UsersTable.js
- src/redux/Reducers/OrderReducer.js
- src/redux/Reducers/usersSlice.js
> feature: users& orders search 

- src/components/ProductsCategories.js
- src/components/home/Products/Product.js
- src/components/home/Products/ProductsGridContainer.js
- src/components/home/Products/wishlistProduct.js
- src/components/our-products/ProductClassCategories.js
- src/components/our-products/ProductSection.js
- src/components/our-products/ourproduct-display.js
- src/dashboard/Components/Orders/Ordersv2/order-card.js
- src/dashboard/Components/Orders/Ordersv2/orders.js
- src/pages/ProductDetails/ProductDetails.js
> Change products display

- src/components/home/Products/Product.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/ProductSubCategory.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/components/pageProps/shopPage/shopBy/Price.js
- src/pages/Default/Shop/Shop.js
- src/pages/Default/Shop/ShopProducts.js
handle component separation while srolling
> fix shop page

- src/components/ProductsCategories.js
- src/pages/Account/Profile/my-address-modal.js
- src/pages/Checkout.js
> fix checkout form default values

- src/components/Header/Header.js
- src/components/homePageCategories/HomePageCategories.js
- src/components/pageProps/shopPage/Accordions/ProductClass.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/components/pageProps/shopPage/ShopSideNav.js
- src/components/pageProps/shopPage/shopBy/Brand.js
- src/components/pageProps/shopPage/shopBy/Color.js
- src/components/pageProps/shopPage/shopBy/NavTitle.js
- src/components/pageProps/shopPage/shopBy/Price.js
- src/pages/Default/Shop/Shop.js
handle change to shop by brand base on class we have implement up and down dropdown icons
> change dropdown functionality on the shop page filters

- src/components/Header/Header.js
- src/components/Header/UserAvatarDropdown.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
> change topheader dropdown positioning

- src/components/Authentication/Enable2Fa.js
- src/components/Authentication/SignInForm.js
- src/components/Authentication/Signinmodal.js
- src/components/Header/Header.js
- src/components/home/Products/Product.js
- src/components/pageProps/shopPage/Accordions/productCategory.js
- src/context/UserContex.js
- src/dashboard/Components/Product/ProductModel/ProductModel.js
- src/dashboard/Components/Product/ProductModel/image-resizer.js
- src/dashboard/Components/ProductClass/AddCategory/Category.js
- src/dashboard/Layouts/LayoutDesign.js
- src/pages/Default/Shop/Shop.js
- src/pages/Payment/cardpayment/card.js
- src/pages/ProductDetails/ProductDetails.js
- src/pages/ProductDetails/ProductMainInfo.js
- src/pages/ProductDetails/SmallImagesContainer.js
> update productimages valiation colors whenever product changes

- src/dashboard/Components/Orders/Ordersv2/single-order/order.js
> add seller paymenent status to the orders product table 
